### PR TITLE
GP-3205: Add CiviRules Action integration

### PR DESCRIPTION
**Pull request by awg-github**

### CODE REVIEW

**Comment by pfigel** [comment]
I didn't change the base branch yet as I think review comments might get marked as outdated if I do that. I'll leave that to you for after the rebasing.

**Comment by pfigel** [comment]
@awg-github Thanks, I think this addresses all the review comments. It still needs to be rebased against `upstream-rules` and the base branch for the PR needs to be changed:

> Also, could you rebase this against the upstream-rules branch in this repo? Upstream has diverged a bit and we'd have some conflicts if we try merging this as-is. upstream-rules matches upstream master plus a pending PR that we have open (adding unit tests).

**Comment by awg-github** [comment]
@pfigel , we need to:

1. Create new branch(`gp_3205_upstream-rules`) from `upstream-rules` branch;
2. Add code from this branch(`gp_3205`) to `gp_3205_upstream-rules` branch;
3. Create new pull request from `gp_3205_upstream-rules` to  `upstream-rules`  branch;

Correct?

**Comment by pfigel** [comment]
@awg-github this should work (assuming the remote for this repo is called `origin`):

    git fetch origin
    git rebase origin/upstream-rules
    # resolve conflict
    git add conflicting-file.php
    git rebase --continue
    # repeat this until all conflicts are resolved
    git push origin gp_3205 -f

I've changed the base branch in this PR, so once that's done it should show as a clean merge here.

Core has some documentation that goes into detail: https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing

**Comment by pfigel** [comment]
@awg-github on second thought, it might be easier to start of with a checkout of `upstream-rules` and run `git cherry-pick` for your commit and resolve the conflicts there. Otherwise it might be messy with the version bump commits and what not.

**Pull request merged**
